### PR TITLE
Updated variable name

### PR DESCRIPTION
**Pull request by is2ei**
I updated variable name to use lower camel case since it is recommended in Scala Style Guide

### CODE REVIEW

**Comment by martijnhoekstra** [comment]
Could you squash these?

**Comment by is2ei** [comment]
sure. just a moment.

**Comment by martijnhoekstra** [comment]
@ihorie is the squashing working out? I could do it myself, but that'd put me as the author of the patch, which would be a dick move.

**Comment by is2ei** [comment]
Sorry for late. I'm working on that and will update soon.

**Comment by is2ei** [comment]
It's done. Could you please review it?

**Comment by martijnhoekstra** [comment]
merged and closed

**Pull request merged**
