### PR TITLE
Update gitignore

### PR DESCRIPTION
**Pull request by is2ei**
I've added '.idea' to gitignore so that we can develop this app using intelliJ.

### CODE REVIEW

**Comment by martijnhoekstra** [comment]
I'm OK with that. Are you planning to work with it already? Let me know what does and doesn't work for you.

**Comment by is2ei** [comment]
Thanks. 
IntelliJ will create .idea directory when it open the project.
I think we don't need to track '.idea' directory so I've added '.idea' to gitignore.

**Comment by martijnhoekstra** [comment]
It's a good idea to have editor-specific paths like .idea in your global .gitignore, but as long as it's not too much clutter I don't mind having it under source control either - I did merge the PR.

What I was asking about was your use of the library. As you can see, it's *very* new, so I'd love any and all feedback, especially about things that you find work well and you find work poorly.

**Comment by is2ei** [comment]
Oh ok. 
I haven't used this library yet.
I sent PR because I thought this is interesting project.

**Pull request merged**
